name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm install
      - run: npm run build --if-present
      - run: npm test

      - name: Build Docker image
        run: docker build -t book-management .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name nodeapp book-management
